apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: real-ai.cn/nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
