apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ui
  namespace: kbaas-qa2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana-ui.example.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
