clusterDomainSuffix: cluster.local
vmselect:
  enabled: true
  name: vmselect
  image:
    repository: victoriametrics/vmselect
    tag: v1.93.6-cluster
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    dedup.minScrapeInterval: 30s
    loggerFormat: json
    loggerTimezone: "Asia/Shanghai"

  horizontalPodAutoscaler:
    enabled: true
    maxReplicas: 4
    minReplicas: 2

  replicaCount: 2
  resources:
    limits:
      cpu: 4096m
      memory: 4096Mi
    requests:
      cpu: 50m
      memory: 64Mi

  cacheMountPath: /cache
  statefulSet:
    enabled: true
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "longhorn"


vminsert:
  enabled: true
  name: vminsert
  image:
    repository: victoriametrics/vminsert
    tag: v1.93.6-cluster
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    replicationFactor: 2
    loggerTimezone: "Asia/Shanghai"

  horizontalPodAutoscaler:
    enabled: true
    maxReplicas: 4
    minReplicas: 2

  resources:
    limits:
      cpu: 4096m
      memory: 4096Mi
    requests:
      cpu: 50m
      memory: 64Mi


vmstorage:
  enabled: true
  name: vmstorage
  image:
    repository: victoriametrics/vmstorage
    tag: v1.93.6-cluster

  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    dedup.minScrapeInterval: 30s
    loggerTimezone: "Asia/Shanghai"
    retentionPeriod: 30d

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: "longhorn"
    mountPath: /storage
    size: 30Gi

  replicaCount: 3
  resources:
    limits:
      cpu: 8192m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 512Mi
