kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'xxxx:587'
      smtp_from: 'username'
      smtp_auth_username: 'username'
      smtp_auth_password: 'userpass'
      smtp_require_tls: true
    templates:
    - '/etc/alertmanager/template/*.tmpl'
    route:
      receiver: default-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 10m
      #routes:
      #  - receiver: alert-sms
      #    match:
      #      severity: sms
      #    group_wait: 10s
      #    repeat_interval: 5m

    receivers:
    - name: default-emailer
      email_configs:
      - to: guang.yang@realai.ai
        send_resolved: false
