apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka1
  labels:
    pv: nfs-kafka1
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "nfs-kafka"
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-kafka
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/k8s_data/kafka1
    server: 10.10.3.27
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka2
  labels:
    pv: nfs-kafka2
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "nfs-kafka"
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-kafka
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/k8s_data/kafka2
    server: 10.10.3.27
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka3
  labels:
    pv: nfs-kafka3
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "nfs-kafka"
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-kafka
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/k8s_data/kafka3
    server: 10.10.3.27