apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: grafana-ui
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: grafana
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  #- type: Resource
  #  resource:
  #    name: cpu
  #    target:
  #      type: AverageValue
  #      averageValue: 5m
