apiVersion: v1
data:
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.eeo.cn/realms/Ldap-test
    clientID: apisix-dev
    clientSecret: KR6oKLIiFJSo9ChGUdtRsi69YWuJIWM5
    requestedScopes: ["openid", "profile", "email", "groups"]
  oidc.tls.insecure.skip.verify: "true"
  url: https://argo.eeo.cn
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
