apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - minio-cred-secret.yaml
  - mysql-cred-secret.yaml
  - workflow-controller-configmap.yaml
  - argo-install-namespaced.yaml
