pyroscope:
  config: |
    pyroscopedb:
      min_free_disk_gb: 10
      min_disk_available_percentage: 0.05
      max_block_duration: 1h
    storage:
      backend: s3
      s3:
        endpoint: "obs.cn-north-4.myhuaweicloud.com"
        bucket_name: ""
        access_key_id: ""
        secret_access_key: ""
        insecure: true
    server:
      http_server_write_timeout: 60s
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      grpc_server_max_concurrent_streams: 100
      log_level: "info"
    distributor:
      pushtimeout: 60s
      pool_config:
        remote_timeout: 10s
        client_cleanup_period: 10s
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: "etcd"
            prefix: "pyroscope/ingester/"
            etcd:
              endpoints: ["loki-etcd.loki.svc.cluster.local:2379"]
              max_retries: 3
              tls_enabled: false
              username: "root"
              password: "ee0^XuFNHMiQ"
          replication_factor: 1
    querier:
      pool_config:
        client_cleanup_period: 10s
        remote_timeout: 5s
      query_store_after: 4h
    frontend:
      scheduler_worker_concurrency: 10
    frontend_worker:
      max_concurrent: 10
    query_scheduler:
      max_outstanding_requests_per_tenant: 100
    store_gateway:
      sharding_ring:
        wait_stability_min_duration: 0s
        kvstore:
          store: "etcd"
          prefix: "pyroscope/store_gateway/"
          etcd:
            endpoints: ["loki-etcd.loki.svc.cluster.local:2379"]
            max_retries: 3
            tls_enabled: false
            username: "root"
            password: "ee0^XuFNHMiQ"
    compactor:
      block_sync_concurrency: 8
      meta_sync_concurrency: 20
      compaction_interval: 30m
      compaction_retries: 3
      compaction_concurrency: 3
      sharding_ring:
        kvstore:
          store: "etcd"
          prefix: "pyroscope/compactor/"
          etcd:
            endpoints: ["loki-etcd.loki.svc.cluster.local:2379"]
            max_retries: 3
            tls_enabled: false
            username: "root"
            password: "ee0^XuFNHMiQ"
    limits:
      compactor_blocks_retention_period: 12h

  components:
    querier:
      kind: Deployment
      replicaCount: 3
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 1
    query-frontend:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 100m
    query-scheduler:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 100m
    distributor:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 500m
    ingester:
      kind: StatefulSet
      replicaCount: 3
      terminationGracePeriodSeconds: 600
      resources:
        limits:
          memory: 16Gi
        requests:
          memory: 4Gi
          cpu: 1
    compactor:
      kind: StatefulSet
      replicaCount: 3
      terminationGracePeriodSeconds: 1200
      persistence:
        enabled: false
      resources:
        limits:
          memory: 16Gi
        requests:
          memory: 2Gi
          cpu: 1
    store-gateway:
      kind: StatefulSet
      replicaCount: 3
      persistence:
        enabled: false
      resources:
        limits:
          memory: 16Gi
        requests:
          memory: 4Gi
          cpu: 1
      readinessProbe:
        initialDelaySeconds: 60
minio:
  enabled: false
agent:
  enabled: false
