---
apiVersion: v1
kind: Service
metadata:
  name: mysql57
spec:
  selector:
    app: mysql57
  ports:
    - name: mysql57
      port: 13306
      protocol: TCP
      targetPort: 3306
  type: NodePort
---
apiVersion: apps/v1beta1
kind: statefulSet
metadata:
  name: mysql57
spec:
  selector:
    matchLabels:
      app: mysql57
  serviceName: mysql57
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql57
    spec:
      containers:
      - image: mysql:5.7
        name: mysql57
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: denglu0416
        ports:
        - containerPort: 3306
          name: mysql57
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-mysql-5.7"
      resources:
        requests:
          storage: 50Gi
