---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pv: nfs-mysql-5.7
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-mysql-5.7
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/mysql-5.7
    server: 10.10.3.27