apiVersion: v1
stringData:
  accesskey: XLZxZD3hX4y9C2Cz
  secretkey: cRee9zl1xvStD8hlfZsh1zSupQGGyH8I
kind: Secret
metadata:
  name: argo-minio-cred
  namespace: argo
  labels:
    app.kubernetes.com/name: minio
type: Opaque
