---
apiVersion: v1
kind: Service
metadata:
  name: mysql57
  namespace: common-middleware
spec:
  selector:
    app: mysql57
  ports:
  - port: 3306
    nodePort: 33306
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql57
  namespace: common-middleware
spec:
  selector:
    matchLabels:
      app: mysql57
  serviceName: mysql57
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql57
    spec:
      containers:
      - image: harbor.bc.kingsoft.com/public/mysql:5.7v1
        name: mysql57
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: denglu0416
        ports:
        - containerPort: 3306
          name: mysql57
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      #tolerations:
      #- key: "key"
      #  operator: "Equal"
      #  value: "value"
      #  effect: "NoExecute"
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi