kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-claim
  namespace: monitoring
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
