kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'smtp.exmail.qq.com:465'
      smtp_from: 'alertmanager'
      smtp_auth_username: 'xxx@eeoa.com'
      smtp_auth_password: 'xxx'
      smtp_require_tls: true
    templates:
    - '/templates/*.tmpl'
    route:
      receiver: default-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 10m
    receivers:
    - name: default-emailer
      email_configs:
      - to: guang.yang@eeoa.com
        send_resolved: false