kubeProxyReplacement: true
k8sServiceHost: 10.252.32.4
k8sServicePort: 8443
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["192.168.64.0/18"]
    clusterPoolIPv4MaskSize: 24
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
    - kafka
bpf:
  masquerade: true
  tproxy: true
gatewayAPI:
  enabled: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
